### ISSUE TITLE
MacOS Mojave From Olarila

### ISSUE THREAD

**Issue by lavrenkov-sketch** [KhaiZeR0/Hackintosh-Dell-inspiron-3458#5]
You link to download MacOS Mojave From Olarila is broken. You can give a new link or suggest where to look?

**Comment by lavrenkov-sketch** [comment]
CATALINA Olarila--

MediaFire Link - https://tinyurl.com/y3mlf4of   

Google Drive Link -  https://tinyurl.com/y3xfbr6q 

Torrent - 
Olarila Catalina.raw.torrent.zip
80.98 kB · 3,815 downloads

MD5 (Olarila Catalina.raw) = b46b17d72e7d813342ec3bcde2df5228
This link is good???

**Comment by khaizr0** [comment]
yes
![image](https://user-images.githubusercontent.com/54585187/102498825-07d74380-40ad-11eb-8a45-9d97a94a2abd.png)
