### ISSUE TITLE
bugfix

### ISSUE THREAD

**Issue by lavrenkov-sketch** [KhaiZeR0/Hackintosh-Dell-inspiron-3458#6]
Hello, can I ask you to describe in more detail how to start wifi work, I have the same laptop as you work, just adding kext itlwm does not write enough that it helliport cannot get the device status, what did you do to start wifi on our laptop
this config is based on your openkore 5.8 added intel wifi and updated kext I'm trying to get Catalina to work.Help me figure out what I'm doing wrong
[config folder url](https://drive.google.com/file/d/1EuVea_fGzNnaNdCVKcwd4mtZb46o-UVD/view?usp=sharing)

[logs](https://drive.google.com/file/d/15wBMQAPqDnJj4LCyKvaZI43txxQkFZfc/view?usp=sharing)

**Comment by khaizr0** [comment]
Try to put it on L/E? (SIP DISABLED) (do as your own risk)

and i will not support the older version of OC (maybe you can try 0.6.0)
